export const ADD_BUN_ELEMENT = 'ADD_BUN_ELEMENT';
export const ADD_NON_BUN_ELEMENT = 'ADD_NON_BUN_ELEMENT';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';
export const UPDATE_ELEMENTS_ORDER = 'UPDATE_ELEMENTS_ORDER';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';
