
export const ADD_BUN_ELEMENT = 'ADD_BUN_ELEMENT';
export const ADD_NON_BUN_ELEMENT = 'ADD_NON_BUN_ELEMENT';
export const SET_ELEMENT_TO_VIEW = 'SET_ELEMENT_TO_VIEW';
export const DELETE_ELEMENT = 'DELETE_ELEMENT';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';
